---
version: 2
snapshots:
- name: "customers"
  description: "This table has basic information about a customer, as well as some\
    \ derived facts based on a customer's orders"
  columns:
  - name: "dbt_valid_to"
    dataType:
      type: "String"
  - name: "first_name"
    description: "Customer's first name. PII."
    tags: []
    dataType:
      type: "String"
  - name: "dbt_updated_at"
    dataType:
      type: "String"
  - name: "customer_id"
    description: "This is a unique identifier for a customer"
    tags: []
    tests:
    - "unique"
    - "not_null"
    dataType:
      type: "Integer"
  - name: "customer_lifetime_value"
    dataType:
      type: "Double"
  - name: "first_order"
    description: "Date (UTC) of a customer's first order"
    tags: []
    dataType:
      type: "Date"
  - name: "dbt_valid_from"
    dataType:
      type: "String"
  - name: "last_name"
    description: "Customer's last name. PII."
    tags: []
    dataType:
      type: "String"
  - name: "dbt_scd_id"
    dataType:
      type: "String"
  - name: "number_of_orders"
    description: "Count of the number of orders a customer has placed"
    tags: []
    dataType:
      type: "Bigint"
  - name: "most_recent_order"
    description: "Date (UTC) of a customer's most recent order"
    tags: []
    dataType:
      type: "Date"
  tests: []
