---
version: 2
models:
- name: "model_p4_OrderBy_1_1"
  tags:
  - "prophecy_temp"
- name: "model_p4_OrderBy_1_1_1"
  tags:
  - "prophecy_temp"
- name: "model_p4_OrderBy_1_1_2"
  tags:
  - "prophecy_temp"
- name: "model_p4_Reformat_1_2"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy__temp_p4_source"
  database: "hive_metastore"
  schema: "arun123"
  tags:
  - "prophecy_temp"
  config:
    enabled: true
  tables:
  - name: "prophecy__temp_p4_post_OrderBy_1_1_0"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_p4_post_OrderBy_1_1_1_0"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_p4_post_OrderBy_1_1_2_0"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_p4_post_Reformat_1_2_0"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_p4_post_SFTPSource_1_0"
    tags:
    - "prophecy_temp"
