---
version: 2
sources:
- name: "hive_metastore.aditya"
  database: "hive_metastore"
  schema: "aditya"
  config:
    enabled: true
  tables:
  - name: "raw_data"
    description: "Raw data capturing values and associated identifiers, serving as\
      \ a foundational dataset for further analysis."
    quoting:
      identifier: true
    columns:
    - name: "id"
      description: "Unique identifier for each record in the dataset"
      dataType:
        type: "Bigint"
    - name: "value"
      description: "The numerical value associated with the record"
      dataType:
        type: "Bigint"
- name: "hive_metastore.rohit"
  database: "hive_metastore"
  schema: "rohit"
  config:
    enabled: true
  tables:
  - name: "raw_orders"
    description: "Order records capturing user transactions and their statuses over\
      \ time."
    quoting:
      identifier: true
    columns:
    - name: "id"
      description: "Unique identifier for each order"
      dataType:
        type: "Bigint"
    - name: "user_id"
      description: "The unique ID of the user who placed the order"
      dataType:
        type: "Bigint"
    - name: "order_date"
      description: "Date when the order was placed"
      dataType:
        type: "Date"
    - name: "status"
      description: "Current status of the order"
      dataType:
        type: "String"
  - name: "raw_customers"
    description: "Customer information including names and identifiers, essential\
      \ for managing customer relationships."
    columns:
    - name: "id"
      description: "Unique identifier for each customer"
      dataType:
        type: "Bigint"
    - name: "first_name"
      description: "The first name of the customer"
      dataType:
        type: "String"
    - name: "last_name"
      description: "The last name of the customer"
      dataType:
        type: "String"
  - name: "databricks123"
    description: "Employee profiles encompassing experience, salary, projects, and\
      \ personal interests, aiding in workforce analysis and resource allocation."
    columns:
    - name: "age"
      description: "The age of the individual"
      dataType:
        type: "Bigint"
    - name: "department"
      description: "The department where the employee works"
      dataType:
        type: "String"
    - name: "experience_years"
      description: "Number of years of professional experience"
      dataType:
        type: "Bigint"
    - name: "hobbies"
      description: "List of hobbies that the individual enjoys"
      dataType:
        type: "Array"
        dataType:
          type: "String"
    - name: "id"
      description: "Unique identifier for each employee"
      dataType:
        type: "Bigint"
    - name: "name"
      description: "The name of the individual"
      dataType:
        type: "String"
    - name: "projects"
      description: "List of projects the individual has worked on, including details\
        \ such as duration and technologies used."
      dataType:
        type: "Array"
        dataType:
          type: "Struct"
          fields:
          - name: "duration"
            dataType:
              type: "Bigint"
            description: "Duration of the project in months"
          - name: "name"
            dataType:
              type: "String"
            description: "Name of the project associated with the employee"
          - name: "technologies"
            dataType:
              type: "Array"
              dataType:
                type: "String"
            description: "Technologies used in the projects undertaken by the individual"
    - name: "salary"
      description: "The annual salary of the employee"
      dataType:
        type: "Double"
  - name: "databricks_flatten_jsonarray"
    description: "Employee profiles encompassing experience, salary, projects, and\
      \ personal interests, aiding in workforce analysis and resource allocation."
    columns:
    - name: "age"
      description: "The age of the individual"
      dataType:
        type: "Bigint"
    - name: "department"
      description: "The department in which the employee works"
      dataType:
        type: "String"
    - name: "experience_years"
      description: "Number of years of professional experience"
      dataType:
        type: "Bigint"
    - name: "hobbies"
      description: "List of hobbies associated with the individual"
      dataType:
        type: "Array"
        dataType:
          type: "String"
    - name: "id"
      description: "Unique identifier for each employee"
      dataType:
        type: "Bigint"
    - name: "name"
      description: "The name of the individual"
      dataType:
        type: "String"
    - name: "projects"
      description: "List of projects the individual has worked on, including details\
        \ such as duration and technologies used."
      dataType:
        type: "Array"
        dataType:
          type: "Struct"
          fields:
          - name: "duration"
            dataType:
              type: "Bigint"
            description: "Duration of the project in months"
          - name: "name"
            dataType:
              type: "String"
            description: "Name of the project associated with the individual"
          - name: "technologies"
            dataType:
              type: "Array"
              dataType:
                type: "String"
            description: "List of technologies used in the projects"
    - name: "salary"
      description: "The annual salary of the employee"
      dataType:
        type: "Double"
  - name: "databricks_null"
    description: "Employee profiles detailing experience, salary, projects, and personal\
      \ interests, aiding in workforce analysis and resource allocation."
    columns:
    - name: "age"
      description: "The age of the employee"
      dataType:
        type: "Bigint"
    - name: "department"
      description: "The department where the employee works"
      dataType:
        type: "String"
    - name: "experience_years"
      description: "Number of years of professional experience"
      dataType:
        type: "Bigint"
    - name: "hobbies"
      description: "List of hobbies associated with the individual"
      dataType:
        type: "Array"
        dataType:
          type: "String"
    - name: "id"
      description: "Unique identifier for each employee"
      dataType:
        type: "Bigint"
    - name: "name"
      description: "The name of the employee"
      dataType:
        type: "String"
    - name: "projects"
      description: "List of projects the individual has worked on, including details\
        \ such as duration and technologies used."
      dataType:
        type: "Array"
        dataType:
          type: "Struct"
          fields:
          - name: "duration"
            dataType:
              type: "Bigint"
            description: "Duration of the project in months"
          - name: "name"
            dataType:
              type: "String"
            description: "Name of the project associated with the employee"
          - name: "technologies"
            dataType:
              type: "Array"
              dataType:
                type: "String"
            description: "Technologies used in the projects undertaken by the individual"
    - name: "salary"
      description: "The annual salary of the employee"
      dataType:
        type: "Double"
  - name: "databricks_large"
    description: "Employee data encompassing experience, salary, age, and personal\
      \ interests, aiding in workforce analysis and departmental insights."
    columns:
    - name: "age"
      description: "The age of the individual"
      dataType:
        type: "Bigint"
    - name: "department"
      description: "The department where the employee works"
      dataType:
        type: "String"
    - name: "experience_years"
      description: "Number of years of professional experience"
      dataType:
        type: "Bigint"
    - name: "hobbies"
      description: "List of hobbies associated with the individual"
      dataType:
        type: "Array"
        dataType:
          type: "String"
    - name: "id"
      description: "Unique identifier for each individual in the dataset"
      dataType:
        type: "Bigint"
    - name: "name"
      description: "The name of the individual"
      dataType:
        type: "String"
    - name: "nested_array"
      description: "A collection of nested arrays containing related data."
      dataType:
        type: "Array"
        dataType:
          type: "Array"
          dataType:
            type: "String"
    - name: "salary"
      description: "Annual salary of the employee"
      dataType:
        type: "Double"
  - name: "nested_arraysjosn"
    description: "Employee profiles encompassing experience, salary, projects, and\
      \ personal interests, aiding in workforce analysis and resource allocation."
    columns:
    - name: "age"
      description: "The age of the employee"
      dataType:
        type: "Bigint"
    - name: "department"
      description: "The department where the employee works"
      dataType:
        type: "String"
    - name: "experience_years"
      description: "Number of years of experience the individual has in their field"
      dataType:
        type: "Bigint"
    - name: "hobbies"
      description: "List of hobbies associated with the individual"
      dataType:
        type: "Array"
        dataType:
          type: "String"
    - name: "id"
      description: "Unique identifier for each employee"
      dataType:
        type: "Bigint"
    - name: "name"
      description: "The name of the employee"
      dataType:
        type: "String"
    - name: "projects"
      description: "List of projects associated with the individual, detailing their\
        \ duration, name, technologies used, and any nested elements."
      dataType:
        type: "Array"
        dataType:
          type: "Struct"
          fields:
          - name: "duration"
            dataType:
              type: "Bigint"
            description: "Duration of the project in months"
          - name: "name"
            dataType:
              type: "String"
            description: "Name of the project associated with the employee"
          - name: "nested_array"
            dataType:
              type: "Array"
              dataType:
                type: "String"
            description: "List of additional items or components related to each project."
          - name: "technologies"
            dataType:
              type: "Array"
              dataType:
                type: "String"
            description: "Technologies used in the projects undertaken by the individual"
    - name: "salary"
      description: "The annual salary of the employee"
      dataType:
        type: "Double"
